experiment_name: mnist_iin

datasets:
  train: iin.data.MNISTTrain
  validation: iin.data.MNISTTest

fid:
  batch_size: 50
fid_stats:
  pre_calc_stat_path: "fid_stats/mnist.npz"

first_stage:
  checkpoint: logs/2020-04-23T00-17-34_mnist_ae/train/checkpoints/model-120000.ckpt
  model: iin.models.ae.Model
  subconfig:
    Model:
      deterministic: false
      in_channels: 1
      in_size: 32
      n_down: 4
      norm: an
      z_dim: 64

model: iin.models.iin.VectorTransformer
Transformer:
  in_channel: 64
  n_flow: 12
  hidden_depth: 2
  hidden_dim: 512
  

loss: iin.losses.iin.Loss

iterator: iin.iterators.iin.Trainer
base_learning_rate: 4.5e-06
batch_size: 25
log_freq: 1000
num_epochs: 50
decay_start: 100001
